project_name: vince
builds:
  - env:
      - CGO_ENABLED=0
      - >-
        {{- if eq .Os "darwin" }}
          {{- if eq .Arch "amd64"}}CC=CC=zig cc -target x86_64-macos-musl{{- end }}
          {{- if eq .Arch "arm64"}}CC=CC=zig cc -target aarch64-macos-musl{{- end }}
        {{- end }}
        {{- if eq .Os "windows" }}
          {{- if eq .Arch "amd64"}}CC=zig cc -target x86_64-windows-musl{{- end }}
          {{- if eq .Arch "arm64"}}CC=zig cc -target aarch64-windows-musl{{- end }}
        {{- end }}
        {{- if eq .Os "linux" }}
          {{- if eq .Arch "amd64"}}CC=zig cc -target x86_64-linux-musl{{- end }}
          {{- if eq .Arch "arm64"}}CC=zig cc -target aarch64-linux-musl{{- end }}
        {{- end }}
      - >-
        {{- if eq .Os "darwin" }}
          {{- if eq .Arch "amd64"}}CXX=CC=zig cc -target x86_64-macos-musl{{- end }}
          {{- if eq .Arch "arm64"}}CXX=CC=zig cc -target aarch64-macos-musl{{- end }}
        {{- end }}
        {{- if eq .Os "windows" }}
          {{- if eq .Arch "amd64"}}CXX=zig cc -target x86_64-windows-musl{{- end }}
          {{- if eq .Arch "arm64"}}CXX=zig cc -target aarch64-windows-musl{{- end }}
        {{- end }}
        {{- if eq .Os "linux" }}
          {{- if eq .Arch "amd64"}}CXX=zig cc -target x86_64-linux-musl{{- end }}
          {{- if eq .Arch "arm64"}}CXX=zig cc -target aarch64-linux-musl{{- end }}
        {{- end }}
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    id: vince
    main: main.go
    binary: vince

  - id: v8s
    main: ./cmd/v8s/main.go
    binary: v8s
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
archives:
  - builds:
      - vince
    id: vince
    name_template: >-
      {{ .Binary }}_
      {{-  .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - man/vince.1
      - completions/vince/*
  - builds:
      - v8s
    id: v8s
    name_template: >-
      {{ .Binary }}_
      {{-  .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - man/v8s.1
      - completions/v8s/*
checksum:
  disable: true
snapshot:
  name_template: "{{ incpatch .Version }}-next"
signs:
  - signature: "${artifact}.minisig"
    cmd: minisign
    artifacts: all
    args:
      - "-Sm"
      - "${artifact}"
    ids:
      - vince
      - v8s
changelog:
  skip: true
dockers:
  - id: vince-amd64
    ids:
      - vince
    image_templates:
      - "ghcr.io/vinceanalytics/vince:{{.Tag}}-amd64"
    skip_push: true
    goos: linux
    goarch: amd64
    dockerfile: "vince.Dockerfile"
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Tag}}"
      - "--platform=linux/amd64"
  - id: vince-arm64
    ids:
      - vince
    image_templates:
      - "ghcr.io/vinceanalytics/vince:{{.Tag}}-arm64"
    skip_push: true
    goos: linux
    goarch: arm64
    dockerfile: "vince.Dockerfile"
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Tag}}"
      - "--platform=linux/arm64"

  - id: v8s-amd64
    ids:
      - v8s
    image_templates:
      - "ghcr.io/vinceanalytics/v8s:{{.Tag}}-amd64"
    skip_push: true
    goos: linux
    goarch: amd64
    dockerfile: "v8s.Dockerfile"
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Tag}}"
      - "--platform=linux/amd64"
  - id: v8s-arm64
    ids:
      - v8s
    image_templates:
      - "ghcr.io/vinceanalytics/v8s:{{.Tag}}-arm64"
    skip_push: true
    goos: linux
    goarch: arm64
    dockerfile: "v8s.Dockerfile"
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Tag}}"
      - "--platform=linux/arm64"

docker_manifests:
  - id: vince
    name_template: "ghcr.io/vinceanalytics/vince:{{.Tag}}"
    image_templates:
      - "ghcr.io/vinceanalytics/vince:{{.Tag}}-amd64"
      - "ghcr.io/vinceanalytics/vince:{{.Tag}}-arm64"
    skip_push: true
  - id: v8s
    name_template: "ghcr.io/vinceanalytics/v8s:{{.Tag}}"
    image_templates:
      - "ghcr.io/vinceanalytics/v8s:{{.Tag}}-amd64"
      - "ghcr.io/vinceanalytics/v8s:{{.Tag}}-arm64"
    skip_push: true
  - id: vince-latest
    name_template: "ghcr.io/vinceanalytics/vince:latest"
    image_templates:
      - "ghcr.io/vinceanalytics/vince:{{.Tag}}-amd64"
      - "ghcr.io/vinceanalytics/vince:{{.Tag}}-arm64"
    skip_push: true
  - id: v8s-latest
    name_template: "ghcr.io/vinceanalytics/v8s:latest"
    image_templates:
      - "ghcr.io/vinceanalytics/v8s:{{.Tag}}-amd64"
      - "ghcr.io/vinceanalytics/v8s:{{.Tag}}-arm64"
    skip_push: true
brews:
  - tap:
      owner: vinceanalytics
      name: homebrew-tap
    commit_author:
      name: Geofrey Ernest
      email: geofreyernest@live.com
    name: vince
    skip_upload: true
    folder: Formula
    homepage: https://winceanalytics.com
    description: The Cloud Native Web Analytics Platform
    license: AGPL-3.0
    ids:
      - vince
    test: |
      system "#{bin}/vince version"
    install: |-
      bin.install "vince"
      bash_completion.install "completions/vince/vince_bash" => "vince"
      zsh_completion.install "completions/vince/vince_zsh" => "_vince"
      man1.install "man/vince.1"
  - tap:
      owner: vinceanalytics
      name: homebrew-tap
    commit_author:
      name: Geofrey Ernest
      email: geofreyernest@live.com
    name: v8s
    skip_upload: true
    folder: Formula
    homepage: https://winceanalytics.com
    description: kubernetes controller for vince- The Cloud Native Web Analytics Platform
    license: AGPL-3.0
    ids:
      - v8s
    test: |
      system "#{bin}/v8s version"
    install: |-
      bin.install "v8s"
      bash_completion.install "completions/v8s/v8s_bash" => "v8s"
      zsh_completion.install "completions/v8s/v8s_zsh" => "_v8s"
      man1.install "man/v8s.1"

# The lines beneath this are called `modelines`. See `:help modeline`
# Feel free to remove those if you don't want/use them.
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj
