---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vince-controller-role
  namespace: {{ .Release.Namespace }}
  labels:
    app: vince
    component: controller
    chart: {{ include "vince.chart" .  | quote }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
rules:
  - apiGroups:
      - staples
    resources:
      - sites
    verbs:
      - get
      - list
      - update
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vince-controller
  namespace: {{ .Release.Namespace }}
  labels:
    app: vince
    component: controller
    chart: {{ include "vince.chart" .  | quote }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: vince-controller-role
subjects:
- kind: ServiceAccount
  name: vince-controller
  namespace: {{ .Release.Namespace }}