---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: v8s-role
  namespace: {{ .Release.Namespace }}
  labels:
    app: vince
    component: controller
    chart: {{ include "v8s.chart" .  | quote }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
rules:
  - apiGroups:
      - staples
    resources:
      - sites
      - vinces
    verbs:
      - get
      - list
      - update
      - watch
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - get 
      - list 
      - watch
      - create
      - update
      - delete
  - apiGroups:
      - apps
    resources:
      - statefulsets
    verbs:
      - get 
      - list 
      - watch
      - create
      - update
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: v8s
  namespace: {{ .Release.Namespace }}
  labels:
    app: vince
    component: controller
    chart: {{ include "v8s.chart" .  | quote }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: v8s-role
subjects:
- kind: ServiceAccount
  name: v8s
  namespace: {{ .Release.Namespace }}