apiVersion: v1
kind: Service
metadata:
  name: v8s
  labels:
    app: vince
    component: controller
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
  selector:
    app: vince
    component: controller
    release: {{ .Release.Name | quote }}
